language: node_js
node_js:
  - "8.0.0"
  - "7.0.0"
  - "6.10"
  - "5.0.0"
  - "4.4.0"
  - "1.0.0"
  - "0.5.5"
  - "0.4.5"
  - "0.3.0"
  - "0.2.1"
  - "0.12.14"
  - "0.10.30"
  - "0.1.20"
script: "npm run-script test"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"